name: Ruby

on: [push,pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1.2
    - name: Run Database
      run: docker run --name=db --network=host -e POSTGRES_HOST_AUTH_METHOD=trust -d postgres
    - name: Run tests
      run: |
        gem install bundler -v 2.3.11
        bundle install
        rake db:create
        rake db:schema:load
        bundle exec rake spec
